### ISSUE TITLE
Failed to construct transformer:  Error: Failed to start watch mode.

### ISSUE THREAD

**Issue by alexandreandriesse** [LegendApp/legend-motion#4]
Hi, I'm facing this error when I run "expo start" after installing legend motion on my existing react native project. It's impossible to run my project. It work perfectly again when I remove Legend Motion.

```
Failed to construct transformer:  Error: Failed to start watch mode.
    at Timeout._onTimeout (C:\path_to_my_project\node_modules\jest-haste-map\build\index.js:928:24)      
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
Error: Failed to start watch mode.
    at Timeout._onTimeout (C:\path_to_my_project\node_modules\jest-haste-map\build\index.js:928:24)      
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

My setup : 

Os: Windows 11,
"expo": "^44.0.0",
"react-native": "0.64.3",
"@babel/core": "^7.12.9",

**Comment by jmeistrich** [comment]
I'm not sure what in Legend Motion would cause that error... I looked up the error and some posts said it could be cause by Node 17+. If you're on that could you try it with Node 16?

**Comment by alexandreandriesse** [comment]
Installing whatchman and cleaning the cache with  "expo start -c" did resolve the issue.

Thanks for your help and reactivity !

**Comment by jmeistrich** [comment]
Great!
